; Implementation of Fibonacci series 
(define (fib n)
 (define (closed)
  (define (enclosed ans prev c)
   (if (<= c 0)
    ans (enclosed prev (+ ans prev)(- c 1))
   )
  )
  (enclosed 1 1 n)
 )
 closed
)

; Checking if a country code is present in a string

(define (getCountryFromCode code)
	(cond
		((equal? code "AF") "Afghanistan")
		((equal? code "AL") "Albania")
		((equal? code "DZ") "Algeria")
		((equal? code "AS") "American Samoa")
		((equal? code "AD") "Andorra")
		((equal? code "AO") "Angola")
		((equal? code "AI") "Anguilla")
		((equal? code "AQ") "Antarctica")
		((equal? code "AG") "Antigua and Barbuda")
		((equal? code "AR") "Argentina")
		((equal? code "AM") "Armenia")
		((equal? code "AW") "Aruba")
		((equal? code "AU") "Australia")
		((equal? code "AT") "Austria")
		((equal? code "AZ") "Azerbaijan")
		((equal? code "BS") "Bahamas (the)")
		((equal? code "BH") "Bahrain")
		((equal? code "BD") "Bangladesh")
		((equal? code "BB") "Barbados")
		((equal? code "BY") "Belarus")
		((equal? code "BE") "Belgium")
		((equal? code "BZ") "Belize")
		((equal? code "BJ") "Benin")
		((equal? code "BM") "Bermuda")
		((equal? code "BT") "Bhutan")
		((equal? code "BO") "Bolivia (Plurinational State of)")
		((equal? code "BQ") "Bonaire, Sint Eustatius and Saba")
		((equal? code "BA") "Bosnia and Herzegovina")
		((equal? code "BW") "Botswana")
		((equal? code "BV") "Bouvet Island")
		((equal? code "BR") "Brazil")
		((equal? code "IO") "British Indian Ocean Territory (the)")
		((equal? code "BN") "Brunei Darussalam")
		((equal? code "BG") "Bulgaria")
		((equal? code "BF") "Burkina Faso")
		((equal? code "BI") "Burundi")
		((equal? code "CV") "Cabo Verde")
		((equal? code "KH") "Cambodia")
		((equal? code "CM") "Cameroon")
		((equal? code "CA") "Canada")
		((equal? code "KY") "Cayman Islands (the)")
		((equal? code "CF") "Central African Republic (the)")
		((equal? code "TD") "Chad")
		((equal? code "CL") "Chile")
		((equal? code "CN") "China")
		((equal? code "CX") "Christmas Island")
		((equal? code "CC") "Cocos (Keeling) Islands (the)")
		((equal? code "CO") "Colombia")
		((equal? code "KM") "Comoros (the)")
		((equal? code "CD") "Congo (the Democratic Republic of the)")
		((equal? code "CG") "Congo (the)")
		((equal? code "CK") "Cook Islands (the)")
		((equal? code "CR") "Costa Rica")
		((equal? code "HR") "Croatia")
		((equal? code "CU") "Cuba")
		((equal? code "CW") "Curaçao")
		((equal? code "CY") "Cyprus")
		((equal? code "CZ") "Czechia")
		((equal? code "CI") "Côte d'Ivoire")
		((equal? code "DK") "Denmark")
		((equal? code "DJ") "Djibouti")
		((equal? code "DM") "Dominica")
		((equal? code "DO") "Dominican Republic (the)")
		((equal? code "EC") "Ecuador")
		((equal? code "EG") "Egypt")
		((equal? code "SV") "El Salvador")
		((equal? code "GQ") "Equatorial Guinea")
		((equal? code "ER") "Eritrea")
		((equal? code "EE") "Estonia")
		((equal? code "SZ") "Eswatini")
		((equal? code "ET") "Ethiopia")
		((equal? code "FK") "Falkland Islands (the) [Malvinas]")
		((equal? code "FO") "Faroe Islands (the)")
		((equal? code "FJ") "Fiji")
		((equal? code "FI") "Finland")
		((equal? code "FR") "France")
		((equal? code "GF") "French Guiana")
		((equal? code "PF") "French Polynesia")
		((equal? code "TF") "French Southern Territories (the)")
		((equal? code "GA") "Gabon")
		((equal? code "GM") "Gambia (the)")
		((equal? code "GE") "Georgia")
		((equal? code "DE") "Germany")
		((equal? code "GH") "Ghana")
		((equal? code "GI") "Gibraltar")
		((equal? code "GR") "Greece")
		((equal? code "GL") "Greenland")
		((equal? code "GD") "Grenada")
		((equal? code "GP") "Guadeloupe")
		((equal? code "GU") "Guam")
		((equal? code "GT") "Guatemala")
		((equal? code "GG") "Guernsey")
		((equal? code "GN") "Guinea")
		((equal? code "GW") "Guinea-Bissau")
		((equal? code "GY") "Guyana")
		((equal? code "HT") "Haiti")
		((equal? code "HM") "Heard Island and McDonald Islands")
		((equal? code "VA") "Holy See (the)")
		((equal? code "HN") "Honduras")
		((equal? code "HK") "Hong Kong")
		((equal? code "HU") "Hungary")
		((equal? code "IS") "Iceland")
		((equal? code "IN") "India")
		((equal? code "ID") "Indonesia")
		((equal? code "IR") "Iran (Islamic Republic of)")
		((equal? code "IQ") "Iraq")
		((equal? code "IE") "Ireland")
		((equal? code "IM") "Isle of Man")
		((equal? code "IL") "Israel")
		((equal? code "IT") "Italy")
		((equal? code "JM") "Jamaica")
		((equal? code "JP") "Japan")
		((equal? code "JE") "Jersey")
		((equal? code "JO") "Jordan")
		((equal? code "KZ") "Kazakhstan")
		((equal? code "KE") "Kenya")
		((equal? code "KI") "Kiribati")
		((equal? code "KP") "Korea (the Democratic People's Republic of)")
		((equal? code "KR") "Korea (the Republic of)")
		((equal? code "KW") "Kuwait")
		((equal? code "KG") "Kyrgyzstan")
		((equal? code "LA") "Lao People's Democratic Republic (the)")
		((equal? code "LV") "Latvia")
		((equal? code "LB") "Lebanon")
		((equal? code "LS") "Lesotho")
		((equal? code "LR") "Liberia")
		((equal? code "LY") "Libya")
		((equal? code "LI") "Liechtenstein")
		((equal? code "LT") "Lithuania")
		((equal? code "LU") "Luxembourg")
		((equal? code "MO") "Macao")
		((equal? code "MG") "Madagascar")
		((equal? code "MW") "Malawi")
		((equal? code "MY") "Malaysia")
		((equal? code "MV") "Maldives")
		((equal? code "ML") "Mali")
		((equal? code "MT") "Malta")
		((equal? code "MH") "Marshall Islands (the)")
		((equal? code "MQ") "Martinique")
		((equal? code "MR") "Mauritania")
		((equal? code "MU") "Mauritius")
		((equal? code "YT") "Mayotte")
		((equal? code "MX") "Mexico")
		((equal? code "FM") "Micronesia (Federated States of)")
		((equal? code "MD") "Moldova (the Republic of)")
		((equal? code "MC") "Monaco")
		((equal? code "MN") "Mongolia")
		((equal? code "ME") "Montenegro")
		((equal? code "MS") "Montserrat")
		((equal? code "MA") "Morocco")
		((equal? code "MZ") "Mozambique")
		((equal? code "MM") "Myanmar")
		((equal? code "NA") "Namibia")
		((equal? code "NR") "Nauru")
		((equal? code "NP") "Nepal")
		((equal? code "NL") "Netherlands (the)")
		((equal? code "NC") "New Caledonia")
		((equal? code "NZ") "New Zealand")
		((equal? code "NI") "Nicaragua")
		((equal? code "NE") "Niger (the)")
		((equal? code "NG") "Nigeria")
		((equal? code "NU") "Niue")
		((equal? code "NF") "Norfolk Island")
		((equal? code "MP") "Northern Mariana Islands (the)")
		((equal? code "NO") "Norway")
		((equal? code "OM") "Oman")
		((equal? code "PK") "Pakistan")
		((equal? code "PW") "Palau")
		((equal? code "PS") "Palestine, State of")
		((equal? code "PA") "Panama")
		((equal? code "PG") "Papua New Guinea")
		((equal? code "PY") "Paraguay")
		((equal? code "PE") "Peru")
		((equal? code "PH") "Philippines (the)")
		((equal? code "PN") "Pitcairn")
		((equal? code "PL") "Poland")
		((equal? code "PT") "Portugal")
		((equal? code "PR") "Puerto Rico")
		((equal? code "QA") "Qatar")
		((equal? code "MK") "Republic of North Macedonia")
		((equal? code "RO") "Romania")
		((equal? code "RU") "Russian Federation (the)")
		((equal? code "RW") "Rwanda")
		((equal? code "RE") "Réunion")
		((equal? code "BL") "Saint Barthélemy")
		((equal? code "SH") "Saint Helena, Ascension and Tristan da Cunha")
		((equal? code "KN") "Saint Kitts and Nevis")
		((equal? code "LC") "Saint Lucia")
		((equal? code "MF") "Saint Martin (French part)")
		((equal? code "PM") "Saint Pierre and Miquelon")
		((equal? code "VC") "Saint Vincent and the Grenadines")
		((equal? code "WS") "Samoa")
		((equal? code "SM") "San Marino")
		((equal? code "ST") "Sao Tome and Principe")
		((equal? code "SA") "Saudi Arabia")
		((equal? code "SN") "Senegal")
		((equal? code "RS") "Serbia")
		((equal? code "SC") "Seychelles")
		((equal? code "SL") "Sierra Leone")
		((equal? code "SG") "Singapore")
		((equal? code "SX") "Sint Maarten (Dutch part)")
		((equal? code "SK") "Slovakia")
		((equal? code "SI") "Slovenia")
		((equal? code "SB") "Solomon Islands")
		((equal? code "SO") "Somalia")
		((equal? code "ZA") "South Africa")
		((equal? code "GS") "South Georgia and the South Sandwich Islands")
		((equal? code "SS") "South Sudan")
		((equal? code "ES") "Spain")
		((equal? code "LK") "Sri Lanka")
		((equal? code "SD") "Sudan (the)")
		((equal? code "SR") "Suriname")
		((equal? code "SJ") "Svalbard and Jan Mayen")
		((equal? code "SE") "Sweden")
		((equal? code "CH") "Switzerland")
		((equal? code "SY") "Syrian Arab Republic")
		((equal? code "TW") "Taiwan (Province of China)")
		((equal? code "TJ") "Tajikistan")
		((equal? code "TZ") "Tanzania, United Republic of")
		((equal? code "TH") "Thailand")
		((equal? code "TL") "Timor-Leste")
		((equal? code "TG") "Togo")
		((equal? code "TK") "Tokelau")
		((equal? code "TO") "Tonga")
		((equal? code "TT") "Trinidad and Tobago")
		((equal? code "TN") "Tunisia")
		((equal? code "TR") "Turkey")
		((equal? code "TM") "Turkmenistan")
		((equal? code "TC") "Turks and Caicos Islands (the)")
		((equal? code "TV") "Tuvalu")
		((equal? code "UG") "Uganda")
		((equal? code "UA") "Ukraine")
		((equal? code "AE") "United Arab Emirates (the)")
		((equal? code "GB") "United Kingdom of Great Britain and Northern Ireland (the)")
		((equal? code "UM") "United States Minor Outlying Islands (the)")
		((equal? code "US") "United States of America (the)")
		((equal? code "UY") "Uruguay")
		((equal? code "UZ") "Uzbekistan")
		((equal? code "VU") "Vanuatu")
		((equal? code "VE") "Venezuela (Bolivarian Republic of)")
		((equal? code "VN") "Viet Nam")
		((equal? code "VG") "Virgin Islands (British)")
		((equal? code "VI") "Virgin Islands (U.S.)")
		((equal? code "WF") "Wallis and Futuna")
		((equal? code "EH") "Western Sahara")
		((equal? code "YE") "Yemen")
		((equal? code "ZM") "Zambia")
		((equal? code "ZW") "Zimbabwe")
		((equal? code "AX") "Åland Islands")
		(else "")
	)
)

(define (countCodes word)
	(if(string-null? word)(+ 0)
		(if(string-null? (getCountryFromCode(string-head word 2))) (countCodes(string-tail word 2))
		(+ 1 (countCodes(string-tail word 2)))
		)
	)
)

(define (sumDigits alp)
	(if(string-null? alp)(+ 0 0)
		(if(string->number(string-head alp 1))(+(string->number(string-head alp 1))(sumDigits(string-tail alp 1)))
		(+(sumDigits(string-tail alp 1)))
		)
	)
)

;Making tuples from two lists

(define(ltuples val list2)
 (if (null? list2)
  '()
  (cons(cons val (car list2))(ltuples val (cdr list2)))
 )
)
  
(define (caltuples list1 list2)
 (if(null? list1)
   '()
   (append(ltuples(car list1)list2)(caltuples(cdr list1)list2))
 )
)